version: 2.1
jobs:
  build:
    environment:
      TZ: /usr/share/zoneinfo/Europe/London
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ arch }}-{{ checksum "package.json" }}
      - run: npm ci
      - save_cache:
          key: dependency-cache-{{ arch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: npm run lint
      - run: npm test
